name: Continuous Integration
on:
  push:
    branches:
      - deploy
      - deploy-staging
jobs:
  requirements:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Fetch unshallow working copy
        with:
          fetch-depth: 0

      - name: Set environment
        run: |
          if [[ $GITHUB_REF_NAME == 'deploy' ]]; then
              echo "CLEVER_APP_ID=${{ secrets.CLEVER_APP_ID_PRODUCTION }}" >> $GITHUB_ENV
          elif [[ $GITHUB_REF_NAME == 'deploy-staging' ]]; then
              echo "CLEVER_APP_ID=${{ secrets.CLEVER_APP_ID_STAGING }}" >> $GITHUB_ENV
          fi

      - uses: 47ng/actions-clever-cloud@v1.3.1
        name: Deploy to Clever Cloud
        with:
          appID: ${{ env.CLEVER_APP_ID }}
          force: true
          quiet: true # disable copying into GitHub Actions all logs from Clever Cloud
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
